version: '2.2'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto_broker
    ports:
      - "1883:1883"  # MQTT protocol port
      - "9001:9001"  # Websockets port
    volumes:
      - ./mosquitto/:/mosquitto/

volumes:
  mosquitto_data: {}   # Defined as a named volume
  mosquitto_log: {}    # Defined as a named volume