# Generated by Django 5.1.5 on 2025-01-27 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='prefix',
        ),
    ]
