# Generated by Django 5.1.5 on 2025-01-27 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_remove_device_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='noise',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='noises', to='device.action'),
            preserve_default=False,
        ),
    ]
